[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

# Set custom sidebar names for multi-page apps
[pages]
"ðŸ“š Homepage" = "app.py"
"ðŸ“Š Reports" = "2_Reports.py"
